### ISSUE TITLE
loadModule timeout

### ISSUE THREAD

**Issue by Thomas101** [kwonoj/hunspell-asm#145]
Hi, firstly thanks for a really great module!

Not sure whether to open this here or `emscripten-wasm-loader`. The issue/request kind of spans both repositories.

We've found that sometimes loading `hunspell-asm` will cause a timeout - normally this is if we're using a development build of electron, or we're doing other things on the machine at loadtime etc. There's a default timeout for loading in `emscripten-wasm-loader` of 3000ms ([constructModule.ts](https://github.com/kwonoj/emscripten-wasm-loader/blob/c25357a8a3bd364f4441b6b3572fa11859993323/src/constructModule.ts#L36)).

The first part of this, is kind of an issue. If an error does occur, the load `loadModule` call rejects the load promise with an error that doesn't indicate that a timeout occured. In our case we get that `fs.mkdir` is not defined. I was wondering if we could provide something more sensible to the promise rejection.

The second part, is that it would be great to pass a configurable timeout to `loadModule()`, so we can decide what constraints to put on the loading. E.g. `loadModule({ timeout: 6000 })` etc.

Would be happy to look at a PR for this, but wanted to check if it's something you're interested in adding before going forward.

Thanks :)

**Comment by kwonoj** [comment]
Yes, for both sounds legit to me. I just peeked into `emscripten-wasm-loader` and I designed `constructModule` itself to accept different timeout number, but haven't exposed into loader itself so no way to access it. 

Feel freely PR against `emscripten-wasm-loader` if you'd like to tackle this - since `hunspell-asm` uses 1.x version still, you may need to PR against 1.x branch: https://github.com/kwonoj/emscripten-wasm-loader/tree/1.x .

On the other hand I'm bit curious why timeout actually would occur - since it doesn't download the binary from remote source I presume 3sec should be sufficient for loading modules.

**Comment by kwonoj** [comment]
and also this module need to expose it into downlevel loader as well, as you mentioned in `loadModule` interface.

**Comment by kwonoj** [comment]
closed via https://github.com/kwonoj/hunspell-asm/releases/tag/v1.1.2 .
